name: Publish
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
      - name: Install dependencies
        run: poetry install
      - name: Build distribution
        run: poetry build
      - name: Publish
        run: poetry publish --username "__token__" --password "${{ secrets.PYPI_TOKEN }}"


  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1

